### ISSUE TITLE
$100 bill looks like $1.00

### ISSUE THREAD

**Issue by fwenzel** [tofumatt/face-value#19]
The USD 100 bill has such small zeroes that it looks like it's really $1.00. Hmmm.

https://skitch.com/fredw/ei34d/usd100

**Comment by tofumatt** [comment]
@sarahsemark, should we try counting the characters of the bills and just decreasing the entire font rather than making the zeros so small? Even I sometimes get tripped up by this on three-digit bills.

We could maybe do it only for bills larger than three digits? Less confusion that way, and then would only apply to a few currencies anyway.

**Comment by sarahmonster** [comment]
The smaller-zeros solution doesn't work (and especially won't work once decimal points are removed—and fraction sizes are decreased—from the translated values below). I'd suggest applying a css classes to the values based on the number of digits, then creating rules for these so we can adjust the sizes that way. In most cases even three digits fits fairly sanely without the zero sizes being decreased.

**Comment by tofumatt** [comment]
Works for me. I'll assign a class to each grouping of text based on the number of characters. `chars-$X` should work.

I'll see about including the symbol in that count as well.

**Comment by fwenzel** [comment]
<3
