### ISSUE TITLE
Offline caching only works intermittently

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/face-value#34]
I was mostly offline when using this throughout eastern Europe. Sometimes it worked and loaded properly, but other times it would just show me a blank screen. I'm not entirely sure what I was doing wrong, but if what I need to do to save the information isn't obvious or user-friendly to me, other people will have the same issues. Not good when standing at a bank machine in the train station of a foreign country at 4am, trying to figure out how much Monopoly money to take out.

**Comment by tofumatt** [comment]
I think the issue is that if offline the update currency code doesn't fail gracefully; the app is cached but there's code that updates the currency data once a day. I think it won't run some JS if it fails (I noticed this bug too).

Matthew Riley MacPherson | http://lonelyvegan.com
(Sent from mobile)
