### ISSUE TITLE
Turkish Lira symbol is missing on iOS

### ISSUE THREAD

**Issue by tofumatt** [tofumatt/face-value#39]
iOS doesn't seem to render the Lira symbol, so perhaps we should use the old symbol. At least until iOS supports the symbol.

Note that the Lira Unicode symbol was only added this year (May 2012).

**Comment by sarahmonster** [comment]
At some point (when design is more finalized) it may make sense to replace certain currency symbols with images (is scaleable svg possible?) in order to have more fine-grained control over their appearance. (See: the lei, which has no symbol but would look better smaller and in all-caps). Alternatively, is there a specific class that can be targeted for each currency "symbol" and then styled appropriately, for the anal-retentive among us?

**Comment by tofumatt** [comment]
I could certainly do the latter, which would probably be more performant as well. We could make raster images of symbols but SVG is a mixed bag and probably won't be very fast on mobile (if it even works).

But I could definitely do the class thing.

**Comment by tofumatt** [comment]
Filed #41 to address this.
